# Deployment YAML file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: propertyappsportal-deploy
  namespace: softspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: propertyappsportal-selector
  template:
    metadata:
      labels:
        app.kubernetes.io/app: propertyappsportal-selector
    spec:
      nodeSelector:
        nodegroup-type: FrontEnd
      # volumes:
      #   - name: efs-assets
      #     persistentVolumeClaim:
      #       claimName: efs-assets-pvc
      containers:
        - name: propertyappsportal-container
          image: 144444637464.dkr.ecr.me-central-1.amazonaws.com/frontend/propertyappsportal:${{ env.IMAGE_TAG }}
          # volumeMounts:
          #   - name: efs-assets
          #     mountPath: /usr/share/nginx/html/images
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
---
# EKS Service Yaml definition
apiVersion: v1
kind: Service
metadata:
  name: propertyappsportal-svc
  namespace: softspace
spec:
  selector:
    app.kubernetes.io/app: propertyappsportal-selector
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 80
---
