name: Build and Push PropertyappsPortal-Frontend Image to AWS ECR
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'kubernetes/**'
    
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: me-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get current time
      id: time
      run: echo "::set-output name=date::$(TZ=Asia/Kolkata date  "+%Y-%m-%d-%H-%M-%S")"

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: frontend/propertyappsportal
        IMAGE_TAG: ${{ steps.time.outputs.date }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
      - name: Image update to Deployment YAML file
      id: image-update
      run: |
        rm -rf kubernetes/deployment.yaml
        cp -pr kubernetes/deployment._copy.yaml kubernetes/deployment.yaml
        echo $IMAGE_TAG
        FILE="kubernetes/deployment.yaml"
        sed -i "s/\$IMAGE_ID/$IMAGE_ID/g" $FILE
        echo "Deployment YAML file updated successfully."
        
        
