name: Build and Push PropertyappsPortal-Frontend Image to AWS ECR
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: me-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Tag the Image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: frontend/propertyappsportal
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

    - name: Confirm before Pushing Image to Amazon ECR
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "Are you sure you want to push the image to Amazon ECR?"
        echo "Type 'yes' to continue, or 'no' to cancel."
        read confirmation
        if [ "$confirmation" != "yes" ]; then
          echo "Aborting the workflow."
          exit 1
        fi

    - name: Push the Image to Amazon ECR
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
